[package]
name = "osshkeys"
description = "A library to read and write OpenSSH public and private keys"
version = "0.1.0"
authors = ["Leo <leo881003@gmail.com>"]
keywords = ["ssh", "ssh-keys", "keys", "openssh"]
repository = "https://github.com/Leo1003/rust-osshkeys"
license = "MIT"
readme = "README.md"
exclude = [".gitignore"]
edition = "2018"

[dependencies]
base64 = "^0.10"
byteorder = "^1.3.1"
openssl = "^0.10.20"
rand = "^0.6.5"
ed25519-dalek = "^1.0.0-pre.1"
cryptovec = "^0.4"
log = "^0.4"
failure = "^0.1.5"
nom_pem = "^4.0"
aes = "^0.3.2"
des = "^0.3.0"
block-modes = "^0.3.3"