[package]
name = "osshkeys"
description = "A library to read and write OpenSSH public and private keys"
version = "0.3.1"
authors = ["Leo <leo881003@gmail.com>"]
keywords = ["ssh", "ssh-keys", "keys", "openssh"]
repository = "https://github.com/Leo1003/rust-osshkeys"
license = "MIT"
readme = "README.md"
exclude = [".gitignore"]
edition = "2018"

[features]
default = ["openssl-cipher"]

# Encrypt/Decrypt by OpenSSL
# For now, there are other parts still depends on OpenSSL,
# therefore, unset this feature won't remove the OpenSSL dependency.
openssl-cipher = []

[dependencies]
base64 = "0.12.0"
byteorder = "1.3.2"
openssl = "0.10.26"
rand = "0.7.2"
ed25519-dalek = "1.0.0-pre.3"
zeroize = "1.1.0"
log = "0.4.8"
failure = "0.1.6"
nom_pem = "4.0.0"
block-modes = "0.3.3"
aes = "0.3.2"
des = "0.3.0"
digest = "0.8.1"
md-5 = "0.8.0"
sha-1 = "0.8.1"
sha2 = "0.8.0"
blowfish = { version = "0.4.0", features = ["bcrypt"] }
aes-ctr = "0.3.0"
stream-cipher = { version = "0.3.2", features = ["std"] }

[dev-dependencies]
hex = "0.4.0"
hex-literal = "0.2.1"
