[package]
name = "osshkeys"
description = "A library to read and write OpenSSH public and private keys"
version = "0.4.2"
authors = ["Leo <leo881003@gmail.com>"]
keywords = ["ssh", "ssh-keys", "keys", "openssh"]
repository = "https://github.com/Leo1003/rust-osshkeys"
license = "MIT"
readme = "README.md"
exclude = [".gitignore"]
edition = "2018"

[features]
default = ["openssl-cipher"]

# Encrypt/Decrypt by OpenSSL
# For now, there are other parts still depends on OpenSSL,
# therefore, unset this feature won't remove the OpenSSL dependency.
openssl-cipher = []

rustcrypto-cipher = ["block-modes", "aes", "aes-ctr", "des", "stream-cipher"]

openssl-vendored = ["openssl/vendored"]

[dependencies]
base64 = "0.12.0"
byteorder = "1.3.2"
openssl = "0.10.30"
rand = "0.7.2"
ed25519-dalek = "1.0.0"
zeroize = "1.1.0"
log = "0.4.8"
backtrace = "0.3.46"
nom_pem = "4.0.0"
digest = "0.9.0"
md-5 = "0.9.0"
sha-1 = "0.9.0"
sha2 = "0.9.0"
bcrypt-pbkdf = "0.3.0"
# cryptovec 0.5 cannot be compiled on Windows
cryptovec = "0.4.6"

# Feature `rustcrypto-cipher` dependencies
block-modes = { version = "0.6.1", optional = true }
aes = { version = "0.5.0", optional = true }
aes-ctr = { version = "0.5.0", optional = true }
des = { version = "0.5.0", optional = true }
stream-cipher = { version = "0.7.1", features = ["std"], optional = true }

[dev-dependencies]
hex = "0.4.0"
hex-literal = "0.2.1"
cfg-if = "0.1.10"
