name: Run Tests
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, 1.40.0, nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run cargo test (with OpenSSL cipher backend)
        uses: actions-rs/cargo@v1
        if: ${{ runner.os != 'Windows' }}
        with:
          command: test
      - name: Run cargo test (with RustCrypto cipher backend)
        uses: actions-rs/cargo@v1
        if: ${{ runner.os != 'Windows' }}
        with:
          command: test
          args: --no-default-features --features=rustcrypto-cipher
      ## Windows
      - name: Run cargo test (with OpenSSL cipher backend)
        uses: actions-rs/cargo@v1
        if: ${{ runner.os == 'Windows' }}
        with:
          command: test
          args: --features=openssl-vendored
      - name: Run cargo test (with RustCrypto cipher backend)
        uses: actions-rs/cargo@v1
        if: ${{ runner.os == 'Windows' }}
        with:
          command: test
          args: --no-default-features --features=rustcrypto-cipher,openssl-vendored
